version: "3.9"
services:
  notebook:
    image: jupyter/teachertools
    build: .
    ports:
      - 127.0.0.1:8888:8888
    container_name:   jupyter_teachertools
    command: "jupyter notebook \
      --NotebookApp.default_url=/lab/ \
      --ip=0.0.0.0 \
      --port=8888 \
      --NotebookApp.token=''"